modLoader = "javafml"
loaderVersion = "[35,)"
license = "MIT" # Want to make your mod open source? Check out https://choosealicense.com/!

[[mods]]
modId = "quests_giver"
version = "${version}"
displayName = "Quests Giver"
displayURL="https://changeme.dev/" #optional
credits="Feywild Community" #optional
authors="Saphie" #optional
description = '''

'''

[[dependencies.quests_giver]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.quests_giver]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"
